# Generated by Django 3.2.4 on 2021-09-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Muffing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=540)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='muffin')),
                ('create', models.DateTimeField(auto_now=True, verbose_name='fecha de modificacion')),
            ],
            options={
                'verbose_name': 'Panquesitos',
            },
        ),
    ]
